name: movi
description: "A new Flutter project."
publish_to: "none"
version: 1.0.1+4

environment:
  sdk: ^3.9.2

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  flutter_riverpod: ^3.0.3
  state_notifier: ^1.0.0
  get_it: ^9.0.5
  go_router: ^16.3.0
  dio: ^5.7.0
  supabase_flutter: ^2.10.0
  google_fonts: ^6.2.1
  sqflite: ^2.3.0
  path: ^1.9.0
  path_provider: ^2.1.2
  sqflite_common_ffi: ^2.3.6
  path_provider_platform_interface: ^2.1.2
  pool: ^1.5.2
  flutter_secure_storage: ^9.2.4
  encrypt: ^5.0.3
  clock: ^1.1.2
  flutter_svg: ^2.0.10+1
  media_kit: ^1.2.2
  media_kit_video: ^2.0.0
  media_kit_libs_video: ^1.0.7
  screen_brightness: ^0.2.2+1
  volume_controller: ^2.0.7
  pip: ^0.0.3
  desktop_multi_window: ^0.2.0
  window_manager: ^0.3.0
  platform: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/app_icon.png
  remove_alpha_ios: true
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: assets/icons/app_icon.png
